[2024-09-07 11:57:11.2183] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=13036

[2024-09-07 11:57:11.2378] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=26256

[2024-09-07 11:57:11.8527] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-09-07 11:57:11.9711] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <3ms>

[2024-09-07 11:57:11.9711] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <107>, Images Number: 2, Unique Items 2

[2024-09-07 11:57:14.3270] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <109ms>

[2024-09-07 11:57:14.3270] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-09-07 11:57:14.5264] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <14ms>

[2024-09-07 11:57:14.5533] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <2ms>

[2024-09-07 11:57:14.5622] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <0ms>

[2024-09-07 11:57:14.5622] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <1ms>

[2024-09-07 11:57:14.5622] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <0ms>

[2024-09-07 11:57:14.5622] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <1ms>

[2024-09-07 11:57:14.8119] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <242ms>

[2024-09-07 11:57:14.8119] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <0ms>

[2024-09-07 11:57:14.8119] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <1ms>

[2024-09-07 11:57:14.8230] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <5ms>

[2024-09-07 11:57:14.8489] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <24ms>

[2024-09-07 11:57:14.8633] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <0ms>

[2024-09-07 11:57:14.8633] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <0ms>

[2024-09-07 11:57:14.8633] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <1ms>

[2024-09-07 11:57:14.8633] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <0ms>

[2024-09-07 11:57:14.9106] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <40ms>

[2024-09-07 11:57:14.9125] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <0ms>

[2024-09-07 11:57:14.9125] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <1ms>

[2024-09-07 11:57:14.9370] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <20ms>

[2024-09-07 11:57:14.9370] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <0ms>

[2024-09-07 11:57:15.3848] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::87]
Successfully read new settings. retryCount=1

[2024-09-07 11:57:15.3848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Service> is <1ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Shell> is <5ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ValueGenerator> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Calculator> is <14ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Registry> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <PowerToys> is <9ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <History> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Uri Handler> is <1ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Unit Converter> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <System Commands> is <24ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\Common\DefaultBrowserInfo.cs::74]
I've tried updating the chosen Web Browser info at least once.

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Indexer> is <3ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Folder> is <4ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Window Walker> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Time and date> is <0ms>

[2024-09-07 11:57:15.4182] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Web Search> is <12ms>

[2024-09-07 11:57:15.4344] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Settings> is <11ms>

[2024-09-07 11:57:16.5393] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::111]
Indexed 51 packaged applications

[2024-09-07 11:57:16.5393] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Package index cost <1014ms>

[2024-09-07 11:57:16.9415] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\PROGRA~2\WINDOW~4\wmplayer.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-07 11:57:17.0016] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\Windows\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-07 11:57:21.2550] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\Win32ProgramRepository.cs::243]
Indexed 894 win32 applications

[2024-09-07 11:57:21.2565] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Win32Program index cost <5728ms>

[2024-09-07 11:57:21.2565] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Program> is <6081ms>

[2024-09-07 11:57:21.2565] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::1333]
Refresh plugins overview

[2024-09-07 11:57:21.2565] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::157]
Begin PowerToys Run startup ----------------------------------------------------
Runtime info:
Version: 0.84.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
End PowerToys Run startup ----------------------------------------------------  


[2024-09-07 11:57:21.2565] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnStartup - Startup cost <7182ms>

[2024-09-07 11:57:21.5248] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
EnvironmentHelper.GetProtectedEnvironmentVariables - Duration cost <0ms>

[2024-09-07 11:57:21.5248] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::100]
RegisterHotkey()

[2024-09-07 11:57:21.5248] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::853]
Set HotKey()

[2024-09-07 11:57:21.5248] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::894]
Registered global hotkey

[2024-09-07 11:58:21.2393] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\ListRepository`1.cs::54]
Item Already Exists <Microsoft Edge.lnk>

[2024-09-07 12:09:10.2468] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.2590] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.2590] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.2590] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.2590] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.2702] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:10.3683] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:21.9722] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:21.9779] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:22.0688] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:09:22.0688] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:12:10.0946] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:12:10.0993] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.Client.WebExperience
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:12:11.3768] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_524.24900.10.0_neutral_~_cw5n1h2txyewy\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\MicrosoftWindows.Client.WebExperience_524.24900.10.0_neutral_~_cw5n1h2txyewy\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8532] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8532] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8532] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8532] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8657] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.8657] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9347] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9347] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9347] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9347] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9441] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:13:45.9441] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:17:30.3764] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.WidgetsPlatformRuntime_1.4.0.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.WidgetsPlatformRuntime_1.4.0.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3896] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3896] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3896] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3993] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3993] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.3993] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 12:38:08.4574] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:06.1918] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftCorporationII.WinAppRuntime.Singleton
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8937] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8994] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8994] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8994] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8994] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:10.8994] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.WindowsNotepad
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Windows.ApplicationModel.Package.get_InstalledLocation()
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:12.1106] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2407.8.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Microsoft.WindowsNotepad_11.2407.8.0_neutral_~_8wekyb3d8bbwe\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-07 15:26:16.2937] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Microsoft.LanguageExperiencePackvi-VN
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:19.4886] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception Clipchamp.Clipchamp
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:26:20.9449] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::88]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Windows.Storage.StorageFolder
		Exception thrown in called method: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
		Possible interpretation of the error: Could not find file 'C:\Program Files\WindowsApps\Clipchamp.Clipchamp_3.1.11620.0_neutral_~_yxz26nhyzhsrt\AppxManifest.xml'.
		Possible resolution: Not yet known

Exception full name  : System.IO.FileNotFoundException
Exception message    : Could not find file 'C:\Program Files\WindowsApps\Clipchamp.Clipchamp_3.1.11620.0_neutral_~_yxz26nhyzhsrt\AppxManifest.xml'.
Exception stack trace:
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Microsoft.Plugin.Program.Programs.UWP.XmlNamespaces(String path)
   at Microsoft.Plugin.Program.Programs.UWP.InitializeAppInfo(String installedLocation)
   at Microsoft.Plugin.Program.Storage.PackageRepository.AddPackage(Package package)
Exception source     : System.Private.CoreLib
Exception target site: Microsoft.Win32.SafeHandles.SafeFileHandle CreateFile(System.String, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, System.IO.FileOptions)
Exception HResult    : -2147024894
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1125] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1159] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1159] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1159] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1159] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1159] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1849] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1849] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1849] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1925] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1925] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 15:45:14.1925] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.5980] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.6247] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.6247] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.6292] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.6292] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.6292] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7374] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7402] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7402] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7402] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7402] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 17:23:03.7402] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Programs\PackageWrapper.cs::56]
-------------------------- Begin exception --------------------------
Message: 	Error status: UNKNOWN
		Program path: Path could not be determined
		Exception thrown in called method: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
		Possible interpretation of the error: Exception MicrosoftWindows.CrossDevice
		Possible resolution: Not yet known

Exception full name  : System.ArgumentException
Exception message    : Value does not fall within the expected range.
Exception stack trace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|39_0(Int32 hr)
   at ABI.Windows.ApplicationModel.IPackageMethods.get_InstalledLocation(IObjectReference _obj)
   at Microsoft.Plugin.Program.Programs.PackageWrapper.GetWrapperFromPackage(Package package)
Exception source     : WinRT.Runtime
Exception target site: Void <ThrowExceptionForHR>g__Throw|39_0(Int32)
Exception HResult    : -2147024809
-------------------------- End exception --------------------------


[2024-09-07 19:22:31.4928] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::206]
Application.Current.SessionEnding

[2024-09-07 19:22:31.4928] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::254]
Start PowerToys Run Exit----------------------------------------------------  

[2024-09-07 19:22:31.5827] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\QueryHistory.json>

[2024-09-07 19:22:31.5827] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\UserSelectedRecord.json>

[2024-09-07 19:22:31.6033] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::97]
Runner with pid=26256 exited. Exiting PowerToys Run

[2024-09-07 19:22:31.6298] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\PowerToysRunSettings.json>

[2024-09-07 19:22:31.6363] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Folder\FolderSettings.json>

[2024-09-07 19:22:31.6363] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Indexer\IndexerSettings.json>

[2024-09-07 19:22:31.6463] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Program\ProgramPluginSettings.json>

[2024-09-07 19:22:31.6463] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-07 19:22:31.6463] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Uri\UriSettings.json>

[2024-09-07 19:22:31.6738] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\ImageCache.json>

[2024-09-07 19:22:31.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::265]
End PowerToys Run Exit ----------------------------------------------------  

[2024-09-07 19:22:31.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnExit - Exit cost <188ms>

[2024-09-07 19:35:05.1771] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::55]
Starting PowerToys Run with PID=26732

[2024-09-07 19:35:05.2059] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::66]
Runner pid=10804

[2024-09-07 19:35:05.3666] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::108]
On Startup.

[2024-09-07 19:35:05.4734] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
ImageLoader.Initialize - Preload images cost <4ms>

[2024-09-07 19:35:05.4734] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Image\ImageLoader.cs::99]
Number of preload images is <107>, Images Number: 2, Unique Items 2

[2024-09-07 19:35:05.5369] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
|Wox.Infrastructure.Alphabet.Initialize|Preload pinyin cache <37ms>

[2024-09-07 19:35:05.5369] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Alphabet.cs::46]
Number of preload pinyin combination<0>

[2024-09-07 19:35:05.8268] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Calculator> is <33ms>

[2024-09-07 19:35:05.8476] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Folder> is <10ms>

[2024-09-07 19:35:05.8647] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <History> is <0ms>

[2024-09-07 19:35:05.9048] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Indexer> is <1ms>

[2024-09-07 19:35:05.9048] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <OneNote> is <0ms>

[2024-09-07 19:35:05.9048] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <PowerToys> is <1ms>

[2024-09-07 19:35:06.2751] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Program> is <352ms>

[2024-09-07 19:35:06.2751] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Registry> is <0ms>

[2024-09-07 19:35:06.2751] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Service> is <1ms>

[2024-09-07 19:35:06.2751] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Shell> is <5ms>

[2024-09-07 19:35:06.2751] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <System Commands> is <5ms>

[2024-09-07 19:35:06.2951] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Time and date> is <1ms>

[2024-09-07 19:35:06.3161] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Unit Converter> is <0ms>

[2024-09-07 19:35:06.3394] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Uri Handler> is <3ms>

[2024-09-07 19:35:06.3394] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <ValueGenerator> is <0ms>

[2024-09-07 19:35:06.3728] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <VS Code Workspaces> is <30ms>

[2024-09-07 19:35:06.3728] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Web Search> is <0ms>

[2024-09-07 19:35:06.3728] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Settings> is <1ms>

[2024-09-07 19:35:06.3952] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Windows Terminal> is <17ms>

[2024-09-07 19:35:06.4162] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::144]
Load cost for <Window Walker> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\SettingsReader.cs::87]
Successfully read new settings. retryCount=1

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Unit Converter> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Calculator> is <33ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Registry> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Time and date> is <1ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Service> is <1ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Shell> is <5ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Web Search> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <ValueGenerator> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <History> is <0ms>

[2024-09-07 19:35:06.6681] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <System Commands> is <5ms>

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\Common\DefaultBrowserInfo.cs::74]
I've tried updating the chosen Web Browser info at least once.

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Window Walker> is <0ms>

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Indexer> is <3ms>

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Folder> is <12ms>

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Uri Handler> is <9ms>

[2024-09-07 19:35:06.6848] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <PowerToys> is <10ms>

[2024-09-07 19:35:06.6962] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Windows Settings> is <12ms>

[2024-09-07 19:35:07.7136] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\PackageRepository.cs::111]
Indexed 51 packaged applications

[2024-09-07 19:35:07.7136] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Package index cost <970ms>

[2024-09-07 19:35:08.5279] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\Windows\syswow64\odbcad32.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-07 19:35:08.5279] [ERROR] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\ShellLinkHelper.cs::169]
-------------------------- Begin exception --------------------------
Message: Failed to fetch description for C:\PROGRA~2\WINDOW~4\wmplayer.exe, Error HRESULT E_FAIL has been returned from a call to a COM component.

Exception full name  : System.Runtime.InteropServices.COMException
Exception message    : Error HRESULT E_FAIL has been returned from a call to a COM component.
Exception stack trace:
   at Wox.Infrastructure.ShellLinkHelper.IShellLinkW.GetDescription(StringBuilder pszName, Int32 cchMaxName)
   at Wox.Infrastructure.ShellLinkHelper.RetrieveTargetPath(String path)
Exception source     : Wox.Infrastructure
Exception target site: Void GetDescription(System.Text.StringBuilder, Int32)
Exception HResult    : -2147467259
-------------------------- End exception --------------------------


[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\Plugins\Microsoft.Plugin.Program\Storage\Win32ProgramRepository.cs::243]
Indexed 894 win32 applications

[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
Microsoft.Plugin.Program.Main - Win32Program index cost <6183ms>

[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Plugin\PluginPair.cs::56]
Total initialize cost for <Program> is <6597ms>

[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::1333]
Refresh plugins overview

[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::157]
Begin PowerToys Run startup ----------------------------------------------------
Runtime info:
Version: 0.84.0.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
End PowerToys Run startup ----------------------------------------------------  


[2024-09-07 19:35:12.9280] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnStartup - Startup cost <7565ms>

[2024-09-07 19:35:13.1104] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
EnvironmentHelper.GetProtectedEnvironmentVariables - Duration cost <0ms>

[2024-09-07 19:35:13.1104] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::100]
RegisterHotkey()

[2024-09-07 19:35:13.1104] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::853]
Set HotKey()

[2024-09-07 19:35:13.1104] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\ViewModel\MainViewModel.cs::894]
Registered global hotkey

[2024-09-07 20:09:14.8048] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\MainWindow.xaml.cs::88]
Send Run settings telemetry

[2024-09-07 21:47:35.3710] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::206]
Application.Current.SessionEnding

[2024-09-07 21:47:35.3710] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::254]
Start PowerToys Run Exit----------------------------------------------------  

[2024-09-07 21:47:35.4810] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\QueryHistory.json>

[2024-09-07 21:47:35.5053] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\UserSelectedRecord.json>

[2024-09-07 21:47:35.5053] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::97]
Runner with pid=10804 exited. Exiting PowerToys Run

[2024-09-07 21:47:35.5718] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\PowerToysRunSettings.json>

[2024-09-07 21:47:35.5718] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Folder\FolderSettings.json>

[2024-09-07 21:47:35.5887] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Indexer\IndexerSettings.json>

[2024-09-07 21:47:35.6018] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Program\ProgramPluginSettings.json>

[2024-09-07 21:47:35.6018] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Shell\ShellPluginSettings.json>

[2024-09-07 21:47:35.6159] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\Plugins\Microsoft.Plugin.Uri\UriSettings.json>

[2024-09-07 21:47:35.6648] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Storage\JsonStorage`1.cs::139]
Saving cached data at <C:\Users\LENOVO LEGION\AppData\Local\Microsoft\PowerToys\PowerToys Run\Settings\ImageCache.json>

[2024-09-07 21:47:35.6813] [INFO] [D:\a\_work\1\s\src\modules\launcher\PowerLauncher\App.xaml.cs::265]
End PowerToys Run Exit ----------------------------------------------------  

[2024-09-07 21:47:35.6813] [INFO] [D:\a\_work\1\s\src\modules\launcher\Wox.Infrastructure\Stopwatch.cs::44]
App.OnExit - Exit cost <304ms>

